### PR TITLE
Add yggio integration

### PR DESCRIPTION
**Pull request by BrandtNick**
https://github.com/Sensative/yggio/issues/554

Uses Yggio mongoDB to pull vsm devices and devEui's for subscription

### CODE REVIEW

**Comment by Sensative-Lars-Mats** [comment]
Thanks for submitting this.
It adds an unconditional dependency to MongoDB which is used only in the yggio integration. My preference would be to make that optional. I am not completely certain how to do that, but I believe that we did something similar to the AWS integration, I believe by making a separate json file for that.

**Comment by Sensative-Lars-Mats** [comment]
Second comment, should there still be a dependency to chirpstack in the Yggio integration?

**Comment by BrandtNick** [comment]
> Thanks for submitting this. It adds an unconditional dependency to MongoDB which is used only in the yggio integration. My preference would be to make that optional. I am not completely certain how to do that, but I believe that we did something similar to the AWS integration, I believe by making a separate json file for that.

Will look into it! Seems AWS dependency is used only inside AWS solver and it's using constants file for its config, I can do something similar.

> Second comment, should there still be a dependency to chirpstack in the Yggio integration?

While it's getting entity id's and devEui's from straight from yggio's database, it's still using chirpstack for subscription/publishing. Using Yggio instead of chirpstack might be doable but would require a lot more work.

**Comment by Sensative-Lars-Mats** [comment]
I appreciate handling the dependency...

As far as the overall requirements set, I do not have a super-strong opinion on the Chirpstack matter, but I suspect it will come right back as soon as a non-chirpstack customer buys any of these devices - the assumption is that Yggio will abstract what underlying LNS is used... however, I think this is actually rather a rest point on the downlink mechanism for Yggio which seems to not yet be unified between different systems.

**Comment by BrandtNick** [comment]
> I appreciate handling the dependency...
> 
> As far as the overall requirements set, I do not have a super-strong opinion on the Chirpstack matter, but I suspect it will come right back as soon as a non-chirpstack customer buys any of these devices - the assumption is that Yggio will abstract what underlying LNS is used... however, I think this is actually rather a rest point on the downlink mechanism for Yggio which seems to not yet be unified between different systems.

I have discussed this with @hakanlundstrom and he and I agrees that we should add support for more than ChirpStack, and use Yggio in the future for subscriptions and downlinks. However, we would like to get this first iteration released and running with ChirpStack first, and then work on a second improved version.

**Comment by Sensative-Lars-Mats** [comment]
OK
________________________________
Från: Nick ***@***.***>
Skickat: den 14 maj 2024 10:17
Till: Sensative/vsm-mqtt-client-open-source ***@***.***>
Kopia: Lars Mats ***@***.***>; Review requested ***@***.***>
Ämne: Re: [Sensative/vsm-mqtt-client-open-source] Add yggio integration (PR #1)


I appreciate handling the dependency...

As far as the overall requirements set, I do not have a super-strong opinion on the Chirpstack matter, but I suspect it will come right back as soon as a non-chirpstack customer buys any of these devices - the assumption is that Yggio will abstract what underlying LNS is used... however, I think this is actually rather a rest point on the downlink mechanism for Yggio which seems to not yet be unified between different systems.

I have discussed this with @hakanlundstrom<https://github.com/hakanlundstrom> and he and I agrees that we should add support for more than ChirpStack, and use Yggio in the future for subscriptions and downlinks. However, we would like to get this first iteration released and running with ChirpStack first, and then work on a second improved version.

**Comment by hakanlundstrom** [comment]
Stämmer, vi måste få en ordentlig integration mot Yggio Connectors. Enda möjligheten att få det att fungera ordentligt för alla kunder samt sälja tjänsten via Yggio. V3.28 kommer snart så kommer inte att hinna fixa det iden.

**Pull request merged**
